include:

### SOFLE ###
    ### BASIC OLED ###
  - board: nice_nano_v2 # LEFT MASTER
    shield: sofle_left
    artifact-name: sofle_oled_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2 # RIGHT
    shield: sofle_right
    artifact-name: sofle_oled_right
  - board: nice_nano_v2 # LEFT PERIPHERAL
    shield: sofle_left_peripheral
    artifact-name: sofle_oled_left_peripheral

    ### ADVANCED OLED ###
  - board: nice_nano_v2 # LEFT MASTER
    shield: sofle_left nice_oled
    artifact-name: sofle_oled_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2 # RIGHT
    shield: sofle_right nice_oled
    artifact-name: sofle_oled_right
  - board: nice_nano_v2 # DONGLE
    shield: sofle_dongle dongle_display
    artifact-name: sofle_oled_dongle
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2 # LEFT PERIPHERAL
    shield: sofle_left_peripheral
    artifact-name: sofle_oled_left_peripheral

### CORNE ###
    ### BASIC OLED ###
  # - board: nice_nano_v2 # LEFT MASTER
    # shield: corne_left
    # artifact-name: corne_oled_left
    # snippet: studio-rpc-usb-uart
  # - board: nice_nano_v2 # RIGHT
    # shield: corne_right
    # artifact-name: corne_oled_right
  # - board: nice_nano_v2 # LEFT PERIPHERAL
    # shield: corne_left_peripheral
    # artifact-name: corne_oled_left_peripheral

### RESET ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk_settings_reset